Lib comparison update
advaith1/libs pull request #191
Opened 2022-11-03 12:58 UTC by Lulalaby

- Added select menu v2 as row
- Checked through all libraries and updated the information about feature, issues and prs

2022-11-03 13:00 UTC, Lulalaby commented
If selectMenuv2 isn't wanted, I can remove it again.
But at least the updated information about libs is useful

2022-11-04 17:26 UTC, BobDotCom commented
Instead of adding a new section for selects v2, maybe update the existing select menus section:
Partial = Support for selects v1
Full = Support for selects v1 & v2

2022-11-04 17:27 UTC, Lulalaby commented
Good shot, might be better.
Waiting for blobs opinion.

2022-11-04 17:46 UTC, advaith1 commented
yeah let's just update the existing column, takes up less space

2022-11-04 17:48 UTC, Lulalaby commented
will do

2022-11-04 18:10 UTC, Lulalaby commented
This might work?

2022-11-16 09:58 UTC, Lulalaby commented
@advaith1 how about a merge :p

2022-11-20 19:38 UTC, AraHaan commented on libs.ts
> +		automod: 'Yes',
I just updated this in my own PR.

2022-11-20 19:38 UTC, AraHaan requested changes

2022-11-20 19:38 UTC, AraHaan commented on libs.ts
> +		forums: 'Yes'
And this too.

2022-11-21 02:43 UTC, Lulalaby commented
@advaith1 can we get this merged?
I saw you merged the other prs recently and it'll probably introduce more merge conflicts if others get merged first

2022-11-22 11:35 UTC, advaith1 commented
imo it would be fine to just remove the asterisks and the note; what do u think?

2022-11-22 11:38 UTC, Lulalaby commented
I honestly think a few metadata infos aren't bad. Your comparison site is pretty known already and I think better than discords. 

It's good to know exact information about all the libs. I would even like to see to go further to have a reliable source for deciding which lib to use, especially for new devs. 

Hope you get what I mean.

2022-11-22 16:39 UTC, Lulalaby commented
yeah. I'm gonna figure something out and respond later with my other idea

2023-01-02 02:19 UTC, merged

2023-01-02 02:19 UTC, Lulalaby commented
Neato, thx blob!