update polls and user apps status
advaith1/libs pull request #254
Opened 2024-04-22 12:30 UTC by MCausc78

dsharpplus
netcord
jda
discordeno
eris
nextcord
disgo
dfx

2024-04-22 18:02 UTC, mlnrDev commented
could you please update the polls status for disgo as well? ty: https://github.com/disgoorg/disgo/pull/346 https://github.com/disgoorg/disgo/releases/tag/v0.18.3

2024-04-27 03:56 UTC, tim-smart commented
Could you add dfx too? https://github.com/tim-smart/dfx/blob/main/src/types.ts#L1204

Saves opening another PR :)

2024-04-29 04:39 UTC, advaith1 requested changes
thanks for the PR! some notes:

2024-04-29 04:39 UTC, advaith1 commented on libs.ts
> +		threads: 'Yes',
looks like threads are only available in the [v3.3.0-M2](https://github.com/Discord4J/Discord4J/releases/tag/3.3.0-M2) prerelease and not in the released version v3.2.6, so this change should be reverted

2024-04-29 04:39 UTC, advaith1 commented on libs.ts
> +		}
looks like this has since been merged

```suggestion
		polls: 'Dev Version'
```

2024-05-04 10:34 UTC, merged